name: News Post Submission
description: 📰 Think we should publish something?
title: ⚠️ Add the name of your post
labels: ["news"]
assignees: [calejvaldez]
body:
  - type: input
    attributes:
      label: Link to file (or folder)
      description: Use the template provided. Link a folder if your post includes images.
      placeholder: https://drive.google.com/...
    validations:
      required: true
  - type: input
    attributes:
      label: Target Date
      description: When should we publish this by?
      placeholder: January 1, 2025
    validations:
      required: true
